#!/bin/sh
color_foreground="#383830"
color_background="#f8f8f2"
color_background_next="#fd971f"
color_separator="#383830"

if [ -z "$color_separator" ]; then
	echo "<span background=\"$color_background_next\" foreground=\"$color_background\"></span><span background=\"$color_background\" foreground=\"$color_foreground\"> `date '+%d.%m.%Y %H:%M:%S'`</span>"
else
	echo "<span background=\"$color_separator\" foreground=\"$color_background\"></span><span background=\"$color_background\" foreground=\"$color_foreground\"> `date '+%d.%m.%Y %H:%M:%S'`</span><span background=\"$color_background\" foreground=\"$color_separator\"></span>"
fi
