#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

color_background="#66d9ef"
color_background_next="#ae81ff"
color_foreground="#383830"
color_separator="#383830"
QUAL="`printf "%03d%%" $QUALITY`"

#if [[ $QUALITY ]]; then
#    printf "%03d%%\n" $QUALITY
#    printf "%03d%%\n" $QUALITY
    #echo $QUALITY% # full text
    #echo $QUALITY% # short text

    # color
#    if [[ $QUALITY -ge 80 ]]; then
#        echo "#73D216"
#    elif [[ $QUALITY -lt 80 ]]; then
#        echo "#EDD400"
#    elif [[ $QUALITY -lt 60 ]]; then
#        echo "#EDD400"
#    elif [[ $QUALITY -lt 40 ]]; then
#        echo "#CC0000"
#    fi
#fi
if [ -z "$color_separator" ]; then
	echo "<span background=\"$color_background_next\" foreground=\"$color_background\"></span><span background=\"$color_background\" foreground=\"$color_foreground\"> $QUAL</span>"
else
	echo "<span background=\"$color_separator\" foreground=\"$color_background\"></span><span background=\"$color_background\" foreground=\"$color_foreground\"> $QUAL</span><span background=\"$color_background\" foreground=\"$color_separator\"></span>"
fi
